# Generated by Django 5.1.3 on 2024-12-05 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_name',
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(default=-2000, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=20, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=30, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=15, verbose_name='Номерной знак'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=20, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='issue_date',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='license_number',
            field=models.CharField(max_length=10, verbose_name='Номер удостоверения'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='license_type',
            field=models.CharField(max_length=10, verbose_name='Тип удостоверения'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.owner', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания владения'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_set', to='project_first_app.owner', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала владения'),
        ),
    ]
